/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 02:25:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.sql.*;

public final class grouptest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String clientId = "zFWHGw63zV5E5AUyx1Ht";
	String clientSecret = "xKgyjz23_I";
	String dbURL = "jdbc:mysql://localhost:3306/naverwep?serverTimezone=UTC";
    String dbID = "root";
    String dbPW = "1234";
	
    String category1 = "인천"; 
	String category2 = "한식";
	String query = category1  + category2;
	String encodedQuery = "";
	try {
		encodedQuery = URLEncoder.encode(query, "UTF-8");
	} catch (UnsupportedEncodingException e) {
		out.println("검색어 인코딩 실패: " + e.getMessage());
	}
	String apiURL = "https://openapi.naver.com/v1/search/local.xml?query=" + encodedQuery
			+ "&display=10&start=1&sort=random";
	HttpURLConnection con = null;
	StringBuilder responseBody = new StringBuilder();

	try {
		URL url = new URL(apiURL);
		con = (HttpURLConnection) url.openConnection();
		con.setRequestMethod("GET");
		con.setRequestProperty("X-Naver-Client-Id", clientId);
		con.setRequestProperty("X-Naver-Client-Secret", clientSecret);
		
		int responseCode = con.getResponseCode();
		InputStream is = (responseCode == 200) ? con.getInputStream() : con.getErrorStream();
		
		BufferedReader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"));
		String line;
		while ((line = reader.readLine()) != null) {
			responseBody.append(line).append("\n");
		}
		reader.close();
	} catch (Exception e) {
	    out.println("오류 발생: " + e.getMessage());
	    e.printStackTrace(new java.io.PrintWriter(out));
	} finally {
		if (con != null)
			con.disconnect();
	}

	javax.xml.parsers.DocumentBuilderFactory factory = javax.xml.parsers.DocumentBuilderFactory.newInstance();
    javax.xml.parsers.DocumentBuilder builder = factory.newDocumentBuilder();
    ByteArrayInputStream xmlStream = new ByteArrayInputStream(responseBody.toString().getBytes("UTF-8"));
    org.w3c.dom.Document doc = builder.parse(xmlStream);

    org.w3c.dom.NodeList items = doc.getElementsByTagName("item");

    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn = DriverManager.getConnection(dbURL, dbID, dbPW);

    String sql = "INSERT INTO companies "
                + "(name, category, address, street_address, description, mapx, mapy, url) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    PreparedStatement pstmt = conn.prepareStatement(sql);

    for (int i = 0; i < items.getLength(); i++) {
        org.w3c.dom.Element item = (org.w3c.dom.Element) items.item(i);

        String name = item.getElementsByTagName("title").item(0).getTextContent();
        String category = item.getElementsByTagName("category").item(0).getTextContent();
        String address = item.getElementsByTagName("address").item(0).getTextContent();
        String streetAddr = item.getElementsByTagName("roadAddress").item(0).getTextContent();
        String description = item.getElementsByTagName("description").item(0).getTextContent();
        String url = item.getElementsByTagName("link").item(0).getTextContent();

        String mapxStr = item.getElementsByTagName("mapx").item(0).getTextContent();
        String mapyStr = item.getElementsByTagName("mapy").item(0).getTextContent();

        double mapx = 0.0;
        double mapy = 0.0;

        try {
            mapx = Double.parseDouble(mapxStr);
            mapy = Double.parseDouble(mapyStr);
        } catch (Exception e) {}

        pstmt.setString(1, name);
        pstmt.setString(2, category);
        pstmt.setString(3, address);
        pstmt.setString(4, streetAddr);
        pstmt.setString(5, description);
        pstmt.setDouble(6, mapx);
        pstmt.setDouble(7, mapy);
        pstmt.setString(8, url);

        pstmt.addBatch();

        out.println("저장됨 → " + name + " / " + category + " / " + address + "<br>");
    }

    pstmt.executeBatch();
    pstmt.close();
    conn.close();
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
